{% set name = "mne-nirs" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ac11a80aa368d6af1884811ae925a8b677e5e391f16fd05e2b39dfcb59f2a6c7

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - mne
    - ipyvtklink
    - seaborn
    - statsmodels

test:
  imports:
    - mne_nirs
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://mne.tools/mne-nirs
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Process Near-Infrared Spectroscopy Data in MNE.
  doc_url: https://mne.tools/mne-nirs
  dev_url: https://github.com/mne-tools/mne-nirs

extra:
  recipe-maintainers:
    - rob-luke
    - hoechenberger
